spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS
    default-property-inclusion: always
    visibility.field: any # for `@Accessors(fluent = true)`
